### ISSUE TITLE
好像ci无法跑过，求指教

### ISSUE THREAD

**Issue by legends-killer** [hackycy/egg-typeorm#8]
按照文档配好之后，可以在dev环境下正常启动，但是在跑ci的时候会报错导致跑不过。
报错如下：
```shell
2021-08-12 15:36:53,219 ERROR 73 nodejs.Error: please config typeorm in config file
  1) "before all" hook in "{root}"
    at new AppBootHook (/github/workspace/node_modules/@hackycy/egg-typeorm/app.js:13:13)

    at /github/workspace/node_modules/egg-core/lib/lifecycle.js:102:45
    at Array.map (<anonymous>)
    at Lifecycle.init (/github/workspace/node_modules/egg-core/lib/lifecycle.js:102:36)
    at AppWorkerLoader.[Loader#loadBootHook] (/github/workspace/node_modules/egg-core/lib/loader/mixin/custom.js:74:20)
    at AppWorkerLoader.loadCustomApp (/github/workspace/node_modules/egg-core/lib/loader/mixin/custom.js:36:25)
    at AppWorkerLoader.load (/github/workspace/node_modules/egg/lib/loader/app_worker_loader.js:35:10)
    at new Application (/github/workspace/node_modules/egg/lib/application.js:66:19)
    at new MessengerApplication (/github/workspace/node_modules/egg-mock/lib/app.js:256:7)
    at MockApplication.[init] (/github/workspace/node_modules/egg-mock/lib/app.js:90:29)
    at Generator.next (<anonymous>)
    at onFulfilled (/github/workspace/node_modules/co/index.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

pid: 73
hostname: f856c6ed2e3c

  0 passing (2s)
  1 failing

  1) "before all" hook in "{root}":
     Error: please config typeorm in config file
      at new AppBootHook (node_modules/@hackycy/egg-typeorm/app.js:13:13)
      at /github/workspace/node_modules/egg-core/lib/lifecycle.js:102:45
      at Array.map (<anonymous>)
      at Lifecycle.init (node_modules/egg-core/lib/lifecycle.js:102:36)
      at AppWorkerLoader.[Loader#loadBootHook] (node_modules/egg-core/lib/loader/mixin/custom.js:74:20)
      at AppWorkerLoader.loadCustomApp (node_modules/egg-core/lib/loader/mixin/custom.js:36:25)
      at AppWorkerLoader.load (node_modules/egg/lib/loader/app_worker_loader.js:35:10)
      at new Application (node_modules/egg/lib/application.js:66:19)
      at new MessengerApplication (node_modules/egg-mock/lib/app.js:256:7)
      at MockApplication.[init] (node_modules/egg-mock/lib/app.js:90:29)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      [use `--full-trace` to display the full stack trace]


```
我没有ignore掉config文件，所以说跑github action插件启动的时候config应该是有值的，但还是报错
本机跑ci也会这样...求指教

**Comment by legends-killer** [comment]
环境试过node14和node12，都不行

**Comment by hackycy** [comment]
ci不是`config.local.ts`配置文件，你先确定好环境是什么，单测是`config.unittest.ts`
具体看egg的运行环境：https://eggjs.org/zh-cn/basics/env.html

**Comment by legends-killer** [comment]
看来是我环境搞错了...没有配测试下的config。感谢~
